/**
 * Standardized error codes. Keep this list append-only — removing or
 * renaming a code is a breaking API change for any client relying on it.
 */
export enum ErrorCode {
  VALIDATION_FAILED = "VALIDATION_FAILED",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  RATE_LIMITED = "RATE_LIMITED",
  INTERNAL_ERROR = "INTERNAL_ERROR",

  // Auth-specific
  EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED",
  MOBILE_ALREADY_REGISTERED = "MOBILE_ALREADY_REGISTERED",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  ACCOUNT_NOT_VERIFIED = "ACCOUNT_NOT_VERIFIED",
  ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED",
  OTP_INVALID = "OTP_INVALID",
  OTP_EXPIRED = "OTP_EXPIRED",
  OTP_MAX_ATTEMPTS = "OTP_MAX_ATTEMPTS",
  REFRESH_TOKEN_INVALID = "REFRESH_TOKEN_INVALID",

  // Profile-specific
  PROFILE_ALREADY_EXISTS = "PROFILE_ALREADY_EXISTS",
  PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND",

  // Interest/Match/Shortlist-specific
  CANNOT_TARGET_SELF = "CANNOT_TARGET_SELF",
  INTEREST_ALREADY_SENT = "INTEREST_ALREADY_SENT",
  INTEREST_NOT_FOUND = "INTEREST_NOT_FOUND",
  INTEREST_ALREADY_RESPONDED = "INTEREST_ALREADY_RESPONDED",
  NOT_INTEREST_RECIPIENT = "NOT_INTEREST_RECIPIENT",
  ALREADY_SHORTLISTED = "ALREADY_SHORTLISTED",
}
